# Generated by Django 3.0.8 on 2020-07-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absent', models.DateField(verbose_name='date abscence')),
                ('reason', models.CharField(blank=True, default='', help_text='some comments about the student', max_length=255, verbose_name='comments')),
            ],
        ),
    ]
