# Generated by Django 3.0.8 on 2020-07-29 23:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0002_presence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presence',
            name='absent',
        ),
        migrations.RemoveField(
            model_name='presence',
            name='reason',
        ),
        migrations.AddField(
            model_name='presence',
            name='Reasson',
            field=models.CharField(blank=True, default='', help_text='some reasson', max_length=255, verbose_name='Reasson'),
        ),
        migrations.AddField(
            model_name='presence',
            name='date_call',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date_call'),
            preserve_default=False,
        ),
    ]
