# Generated by Django 3.0.8 on 2020-08-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0003_auto_20200729_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='ismissing',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='presence',
            name='Reasson',
            field=models.CharField(blank=True, default='', help_text='tell why the student is missing', max_length=255, verbose_name='Reasson'),
        ),
    ]
