# Generated by Django 3.0.8 on 2020-08-01 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0004_auto_20200801_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lycee.Student'),
        ),
    ]
