# Generated by Django 3.0.8 on 2020-08-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0006_auto_20200807_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='ismissing',
            field=models.BooleanField(default=False),
        ),
    ]
